import {
  Phone,
  Video,
  Paperclip,
  Camera,
  Mic,
  Heart,
  ShoppingCart,
  Home,
  User,
  Settings,
  Search,
  Plus,
  X,
  ArrowLeft,
  ArrowRight,
} from "lucide-react";

export const Icons = {
  phone: (props: any) => <Phone size={18} {...props} />,
  video: (props: any) => <Video size={18} {...props} />,
  attach: (props: any) => <Paperclip size={18} {...props} />,
  camera: (props: any) => <Camera size={18} {...props} />,
  mic: (props: any) => <Mic size={18} {...props} />,
  heart: (props: any) => <Heart size={18} {...props} />,
  cart: (props: any) => <ShoppingCart size={18} {...props} />,
  home: (props: any) => <Home size={18} {...props} />,
  user: (props: any) => <User size={18} {...props} />,
  settings: (props: any) => <Settings size={18} {...props} />,
  search: (props: any) => <Search size={18} {...props} />,
  plus: (props: any) => <Plus size={18} {...props} />,
  close: (props: any) => <X size={18} {...props} />,
  back: (props: any) => <ArrowLeft size={22} {...props} />,
  forward: (props: any) => <ArrowRight size={22} {...props} />,
};
